//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsCatIndicadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdsCatIndicadores()
        {
            this.IdsBitacora = new HashSet<IdsBitacora>();
            this.IdsIndicadores = new HashSet<IdsIndicadores>();
            this.IdsIndicadorAnual = new HashSet<IdsIndicadorAnual>();
            this.IdsIndicadores1 = new HashSet<IdsIndicadores>();
            this.IdsIndicadorAnual1 = new HashSet<IdsIndicadorAnual>();
            this.IdsIndicadores2 = new HashSet<IdsIndicadores>();
            this.IdsIndicadores3 = new HashSet<IdsIndicadores>();
            this.IdsIndicadores4 = new HashSet<IdsIndicadores>();
            this.IdsMediciones = new HashSet<IdsMediciones>();
            this.IdsMensualesPorMontos = new HashSet<IdsMensualesPorMontos>();
            this.IdsDesgloseIndicadores = new HashSet<IdsDesgloseIndicadores>();
            this.IdsIndicadorAnual2 = new HashSet<IdsIndicadorAnual>();
            this.IdsRelaciones = new HashSet<IdsRelaciones>();
        }
    
        public int IdsIdIndicador { get; set; }
        public string IdsDescripcionIndicador { get; set; }
        public string IdsIdUnidad { get; set; }
        public string IdsNotasAdicionales { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsBitacora> IdsBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadores> IdsIndicadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadorAnual> IdsIndicadorAnual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadores> IdsIndicadores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadorAnual> IdsIndicadorAnual1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadores> IdsIndicadores2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadores> IdsIndicadores3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadores> IdsIndicadores4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsMediciones> IdsMediciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsMensualesPorMontos> IdsMensualesPorMontos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsDesgloseIndicadores> IdsDesgloseIndicadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsIndicadorAnual> IdsIndicadorAnual2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsRelaciones> IdsRelaciones { get; set; }
    }
}
