//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsCatElementos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdsCatElementos()
        {
            this.IdsBitacora = new HashSet<IdsBitacora>();
            this.IdsMediciones = new HashSet<IdsMediciones>();
            this.IdsDesgloseIndicadores = new HashSet<IdsDesgloseIndicadores>();
            this.IdsRelaciones = new HashSet<IdsRelaciones>();
        }
    
        public int IdsIdElemento { get; set; }
        public string IdsNomenclatura { get; set; }
        public string IdsIdentificador { get; set; }
        public string IdsDescripcionElemento { get; set; }
        public int IdsUnidad { get; set; }
        public string IdsNotas { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }
        public Nullable<bool> IdsTipoCambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsBitacora> IdsBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsMediciones> IdsMediciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsDesgloseIndicadores> IdsDesgloseIndicadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsRelaciones> IdsRelaciones { get; set; }
    }
}
