//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class IdsDesgloseIndicadores
    {
        public int IdsId { get; set; }
        [DisplayName("Planta")]
        public int IdsIdEmpresa { get; set; }
        [DisplayName("Año")]
        public int IdsAnio { get; set; }
        [DisplayName("Indicadores")]
        public int IdsIdIndicador { get; set; }
        [DisplayName("Descripcion de Medicion")]
        public int IdsIdMedicion { get; set; }
        [DisplayName("Elementos")]
        public Nullable<int> IdsIdElemento { get; set; }
        [DisplayName("Unidad de Medida")]
        public Nullable<int> IdsIdUnidad { get; set; }
        [DisplayName("Se Calcula")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public string IdsTipoDeCalculo { get; set; }
        public string IdsStatus { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }

        public virtual IdsCatElementos IdsCatElementos { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores { get; set; }
        public virtual IdsCatMediciones IdsCatMediciones { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades { get; set; }
    }
}
