//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsFormulas
    {
        public int IdsId { get; set; }
        public int IdsIdEmpresa { get; set; }
        public int IdsIdaCalcular { get; set; }
        public int IdsIdElemento { get; set; }
        public int IdsOrden { get; set; }
        public string IdsValor { get; set; }
        public string IdsTipoOperador { get; set; }
        public int IdsIdRaiz { get; set; }
        public int IdsIndicadorOrigen { get; set; }
        public string IdsTipoDato { get; set; }
        public int IdsUnidad { get; set; }
        public bool IdsStatus { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }
    }
}
