//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class IdsIndicadores
    {
        public int IdsId { get; set; }
        [DisplayName("Planta")]
        public int IdsIdEmpresa { get; set; }
        [DisplayName("Mes")]
        public int IdsMes { get; set; }
        [DisplayName("Año")]
        public int IdsAnio { get; set; }
        [DisplayName("Indicadores")]
        public int IdsIdIndicador { get; set; }
        [DisplayName("Descripcion de Indicador")]
        public string IdsDescripcionIndicador { get; set; }
        [DisplayName("Unidad de Medida")]
        public Nullable<int> IdsIdUnidad { get; set; }
        [DisplayName("Se Calcula")]
        //[DisplayFormat(DataFormatString = "{0:##,###,###.###}")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public double IdsValorDelPeriodo { get; set; }
        [DisplayName("Notas")]
        public string IdsNotasAdicionales { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }

        public virtual IdsCatEmpresas IdsCatEmpresas { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas1 { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas2 { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas3 { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas4 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores1 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores2 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores3 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores4 { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades1 { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades2 { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades3 { get; set; }
        public virtual IdsCatUnidades IdsCatUnidades4 { get; set; }
    }
}
