//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class IdsIndicadorAnual
    {
        [DisplayName("Planta")]
        public int IdsIdEmpresa { get; set; }
        [DisplayName("indicadores")]
        public int IdsIdIndicador { get; set; }
        [DisplayName("Ene.")]
        public Nullable<int> IdsMesEnero { get; set; }
        [DisplayName("Feb.")]
        public Nullable<int> IdsMesFebrero { get; set; }
        [DisplayName("Mzo.")]
        public Nullable<int> IdsMesMarzo { get; set; }
        [DisplayName("Abr.")]
        public Nullable<int> IdsMesAbril { get; set; }
        [DisplayName("May.")]
        public Nullable<int> IdsMesMayo { get; set; }
        [DisplayName("Jun.")]
        public Nullable<int> IdsMesJunio { get; set; }
        [DisplayName("Jul.")]
        public Nullable<int> IdsMesJulio { get; set; }
        [DisplayName("Ago.")]
        public Nullable<int> IdsMesAgosto { get; set; }
        [DisplayName("Sep.")]
        public Nullable<int> IdsMesSeptiembre { get; set; }
        [DisplayName("Oct.")]
        public Nullable<int> IdsMesOctubre { get; set; }
        [DisplayName("Nov.")]
        public Nullable<int> IdsMesNoviembre { get; set; }
        [DisplayName("Dic.")]
        public Nullable<int> IdsMesDiciembre { get; set; }
        [DisplayName("Anual")]
        public Nullable<int> IdsAnual { get; set; }
        public Nullable<int> IdsAnio { get; set; }
        public Nullable<int> IdsUsuario { get; set; }

        public virtual IdsCatEmpresas IdsCatEmpresas { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas1 { get; set; }
        public virtual IdsCatEmpresas IdsCatEmpresas2 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores1 { get; set; }
        public virtual IdsCatIndicadores IdsCatIndicadores2 { get; set; }
    }
}
