//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsPantallasPermisos
    {
        public int idPantallasPermisos { get; set; }
        public int IdPantalla { get; set; }
        public int IdUsuario { get; set; }
    }
}
