//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsPermisosPlantas
    {
        public int IdsId { get; set; }
        public int IdsIdEmpresa { get; set; }
        public string Empresa { get; set; }
        public int IdsIdUsuario { get; set; }
        public Nullable<System.DateTime> IdsFechaAlta { get; set; }
        public Nullable<int> IdsUsuarioAlta { get; set; }
        public Nullable<System.DateTime> IdsFechaCambio { get; set; }
        public Nullable<int> IdsUsuarioCambio { get; set; }
        public Nullable<bool> IdsPlantaDefault { get; set; }
    
        public virtual IdsCatEmpresas IdsCatEmpresas { get; set; }
        public virtual IdsUsuario IdsUsuario { get; set; }
    }
}
