//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsSubirMateriaPrima
    {
        public int IdsId { get; set; }
        public string ano_mes { get; set; }
        public string ci { get; set; }
        public string planta { get; set; }
        public string subalmacen { get; set; }
        public string codificador { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> cantidad_consumida { get; set; }
    }
}
