//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYDSA_Sustentabilidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class IdsUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdsUsuario()
        {
            this.IdsPermisosPlantas = new HashSet<IdsPermisosPlantas>();
        }

        public int IdsIdUsuario { get; set; }
        [DisplayName("Planta")]
        public Nullable<int> IdsIdEmpresa { get; set; }
        public int IdsRol_id { get; set; }
        [DisplayName("Usuario")]
        public string IdsNombreUsuario { get; set; }
        [DisplayName("Correo")]
        public string IdsCorreo { get; set; }
        [DisplayName("Contraseña")]
        public string IdsPassword { get; set; }

        public Nullable<bool> Estatus { get; set; }
 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdsPermisosPlantas> IdsPermisosPlantas { get; set; }
        public virtual IdsRol IdsRol { get; set; }
        public virtual IdsRol IdsRol1 { get; set; }
    }
}
